Load and read JSON

In [1]:
import pandas as pd
df=pd.read_json('../ex02/auto.json')
df=df.set_index('CarNumber')
df.head()

              Refund   Fines    Make  Model
CarNumber
Y163O8161RUS       2  3200.0    Ford  Focus
E432XX77RUS        1  6500.0  Toyota  Camry
7184TT36RUS        1  2100.0    Ford  Focus
X582HE161RUS       2  2000.0    Ford  Focus
92918M178RUS       1  5700.0    Ford  Focus

Rows where fines are greater than 2100

In [2]:
df[df['Fines']>2100]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

 Rows where fines are greater than 2100 and refund equals 2

In [3]:
df[(df['Fines']>2100)&(df['Refund']==2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

Rows where the model is from the list
Focus and Corolla

In [4]:
df[df['Model'].isin(['Focus', 'Corolla'])]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

Rows where the car number is from the list

In [5]:
df.loc[
    ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
]

              Refund          Fines  Make  Model
CarNumber
Y7689C197RUS       1   27000.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       1    8594.586466  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus

Median fines grouped by make

In [6]:
df.groupby('Make')['Fines'].median()

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

Median fines grouped by make and model

In [7]:
df.groupby(['Make', 'Model'])['Fines'].median()

Make        Model
Audi                   4200.0
BMW                    6500.0
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen             7400.0
            Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Volvo                  8500.0
Name: Fines, dtype: float64

Minimum and maximum fines grouped by make and model

In [8]:
df.groupby(['Make', 'Model'])['Fines'].agg(['min', 'max'])

                       min            max
Make       Model
Audi                4200.0    4200.000000
BMW                 3000.0    8594.586466
Ford       Focus     100.0  180000.000000
           Mondeo   1100.0   46200.000000
Skoda      Octavia   300.0  145000.000000
Toyota     Camry     500.0   22400.000000
           Corolla   900.0   34300.000000
Volkswagen          1300.0    7900.000000
           Golf      200.0  168000.000000
           Jetta     500.0   46000.000000
           Passat    100.0   29700.000000
           Touareg   500.0    8594.586466
Volvo               6800.0   10200.000000

Display the standard deviation of fines grouped by make and model to better understand the variance.

In [9]:
df.groupby(['Make', 'Model'])['Fines'].std()

Make        Model
Audi                            NaN
BMW                     2826.561226
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen              3674.688195
            Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Volvo                   2404.163056
Name: Fines, dtype: float64

Display the car numbers, grouped by the number of fines in descending order. We want to find those who most often violated the law.

In [10]:
df.groupby(['CarNumber'])['Fines'].agg('count').sort_values(ascending=False)

CarNumber
Y7689C197RUS    4
92928M178RUS    4
7788KT197RUS    4
H115YO163RUS    3
X758HY197RUS    3
               ..
E42577152RUS    1
E42377152RUS    1
E41977152RUS    1
E41577152RUS    1
H917TC36RUS     1
Name: Fines, Length: 531, dtype: int64

Top-1 Fines Cars

In [11]:
df.loc['Y7689C197RUS']

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus

Most paid

In [12]:
df.groupby(['CarNumber'])['Fines'].agg('sum').sort_values(ascending=False)

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
83218C154RUS       100.0
Y195O8161RUS       100.0
K376HE161RUS       100.0
705787163RUS       100.0
K326T8197RUS       100.0
Name: Fines, Length: 531, dtype: float64

top-1 for most paid

In [13]:
df.loc['X758HY197RUS']

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

Are there any car numbers connected to different models?

In [14]:
df.groupby('CarNumber')['Model'].nunique().sort_values(ascending=False)

CarNumber
E316EH197RUS    2
704687163RUS    1
O64297197RUS    1
O481OH77RUS     1
O49797197RUS    1
               ..
C299K9154RUS    1
9975CC77RUS     1
9943OH154RUS    1
9943KK197RUS    1
Y973O8197RUS    1
Name: Model, Length: 531, dtype: int64