Read the CSV file

In [14]:
import pandas as pd

df = pd.read_csv('../data/auto.csv', index_col='ID')
df.head()

       CarNumber  Make_n_model  Refund   Fines  History
ID
0   Y163O8161RUS    Ford Focus     2.0  3200.0      NaN
1    E432XX77RUS  Toyota Camry     1.0  6500.0      NaN
2    7184TT36RUS    Ford Focus     1.0  2100.0      NaN
3   X582HE161RUS    Ford Focus     2.0  2000.0      NaN
4   E34877152RUS    Ford Focus     2.0  6100.0      NaN

Count the number of observations

In [15]:
df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

Drop duplicates

In [16]:
df = df.drop_duplicates(
    subset=['CarNumber', 'Make_n_model', 'Fines'],
    keep='last'
)
df.head()

       CarNumber  Make_n_model  Refund   Fines  History
ID
0   Y163O8161RUS    Ford Focus     2.0  3200.0      NaN
1    E432XX77RUS  Toyota Camry     1.0  6500.0      NaN
2    7184TT36RUS    Ford Focus     1.0  2100.0      NaN
3   X582HE161RUS    Ford Focus     2.0  2000.0      NaN
5   92918M178RUS    Ford Focus     1.0  5700.0      NaN

In [17]:
df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

Check how many values are missing from each column.

In [18]:
df.isna().sum()

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

Drop columns

In [19]:

df['Refund'].mean()

np.float64(1.5133239831697054)

In [20]:
df = df.dropna(axis=1, thresh=df.shape[0] - 500)
df.isna().sum()

CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

Fill missing values in Refund

In [21]:
df['Refund'] = df['Refund'].fillna(method='ffill')
df.isna().sum()

/var/folders/mv/cndzwjh57k553y8tywr8tmg80000gn/T/ipykernel_5138/1896196157.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Refund'] = df['Refund'].fillna(method='ffill')

CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

Fill missing values in Fines
Replace missing values with the mean value of the column.

In [22]:
df['Fines'] = df['Fines'].fillna(df['Fines'].mean())
df.isna().sum()

CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

Split and parse Make_n_model

In [23]:
df['Make'] = df['Make_n_model'].apply(lambda x: x.split()[0])
df['Model'] = df['Make_n_model'].apply(lambda x: ' '.join(x.split()[1:]))
df.head()

       CarNumber  Make_n_model  Refund   Fines    Make  Model
ID
0   Y163O8161RUS    Ford Focus     2.0  3200.0    Ford  Focus
1    E432XX77RUS  Toyota Camry     1.0  6500.0  Toyota  Camry
2    7184TT36RUS    Ford Focus     1.0  2100.0    Ford  Focus
3   X582HE161RUS    Ford Focus     2.0  2000.0    Ford  Focus
5   92918M178RUS    Ford Focus     1.0  5700.0    Ford  Focus

Drop Make_n_model

In [24]:
df = df.drop(columns=['Make_n_model'])
df.head()

       CarNumber  Refund   Fines    Make  Model
ID
0   Y163O8161RUS     2.0  3200.0    Ford  Focus
1    E432XX77RUS     1.0  6500.0  Toyota  Camry
2    7184TT36RUS     1.0  2100.0    Ford  Focus
3   X582HE161RUS     2.0  2000.0    Ford  Focus
5   92918M178RUS     1.0  5700.0    Ford  Focus

Save the dataframe to JSON

In [25]:
df.to_json('auto.json', orient='records')