In [28]:
import pandas as pd
import numpy as np
import requests

Read the JSON file from ex02

In [29]:
pd.options.display.float_format = '{:.2f}'.format
df = pd.read_json('../ex02/auto.json')
df.head()

      CarNumber  Refund   Fines    Make  Model
0  Y163O8161RUS       2 3200.00    Ford  Focus
1   E432XX77RUS       1 6500.00  Toyota  Camry
2   7184TT36RUS       1 2100.00    Ford  Focus
3  X582HE161RUS       2 2000.00    Ford  Focus
4  92918M178RUS       1 5700.00    Ford  Focus

Create a sample of 200 new observations

In [30]:
sample = df.sample(n=200, replace=True, random_state=21)
sample.head()

        CarNumber  Refund   Fines        Make   Model
207  Y351O8197RUS       1 1500.00        Ford   Focus
48    H917TC36RUS       2 4000.00        Ford   Focus
368  C589EY154RUS       1 4500.00        Ford   Focus
120   K846YE77RUS       2 2000.00  Volkswagen  Passat
419  X4108H125RUS       2 1300.00        Ford   Focus

Concatenate the sample with the initial dataframe

In [31]:
concat_rows = pd.concat([df, sample], ignore_index=True)
concat_rows.tail()

        CarNumber  Refund    Fines        Make   Model
920  M942OT152RUS       1  2000.00        Ford   Focus
921  Y187O8161RUS       2   400.00        Ford   Focus
922  7064C8197RUS       1 12800.00  Volkswagen  Passat
923  8437XX154RUS       2   800.00        Ford   Focus
924   C410X938RUS       2  2200.00        Ford   Focus

Enrich the concat_rows dataframe with a new column containing gen

In [32]:
np.random.seed(21)

year = pd.Series(
    np.random.randint(1980, 2020, size=len(concat_rows)),
    name='Year'
)

fines = pd.concat([concat_rows, year], axis=1)

fines.head()

      CarNumber  Refund   Fines    Make  Model  Year
0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
2   7184TT36RUS       1 2100.00    Ford  Focus  1984
3  X582HE161RUS       2 2000.00    Ford  Focus  2015
4  92918M178RUS       1 5700.00    Ford  Focus  2014

In [33]:
surnames = pd.read_json('../data/surname.json')
surnames.head()

          0       1     2
0      NAME   COUNT  RANK
1     ADAMS  427865    42
2     ALLEN  482607    33
3   ALVAREZ  233983    92
4  ANDERSON  784404    15

In [34]:
surnames.columns = surnames.iloc[0]
surnames = surnames.iloc[1:].reset_index(drop=True)
surnames.head()

0      NAME   COUNT RANK
0     ADAMS  427865   42
1     ALLEN  482607   33
2   ALVAREZ  233983   92
3  ANDERSON  784404   15
4    BAILEY  277845   72

Create a series with surnames

In [35]:
surname_series = surnames['NAME'].str.replace(r'[^A-Z]', '', regex=True)
surname_series.head()

0       ADAMS
1       ALLEN
2     ALVAREZ
3    ANDERSON
4      BAILEY
Name: NAME, dtype: object

Unique car numbers

In [36]:
unique_car_numbers = pd.Series(sample['CarNumber'].unique(), name='CarNumber')
unique_car_numbers.head()

0    Y351O8197RUS
1     H917TC36RUS
2    C589EY154RUS
3     K846YE77RUS
4    X4108H125RUS
Name: CarNumber, dtype: object

Sample surnames for owners

In [37]:
surname_sample = surname_series.sample(
    n=len(unique_car_numbers),
    random_state=21,
    replace=True
).reset_index(drop=True)

surname_sample.head()

0    RICHARDSON
1          ROSS
2        MORGAN
3        BAILEY
4         LOPEZ
Name: NAME, dtype: object

Create the owners dataframe

In [38]:
owners = pd.DataFrame({
    'CarNumber': unique_car_numbers.reset_index(drop=True),
    'SURNAME': surname_sample
})

owners.head()

      CarNumber     SURNAME
0  Y351O8197RUS  RICHARDSON
1   H917TC36RUS        ROSS
2  C589EY154RUS      MORGAN
3   K846YE77RUS      BAILEY
4  X4108H125RUS       LOPEZ

Append five new observations to the fines dataframe

In [39]:
new_fines = pd.DataFrame({
    'CarNumber': ['A001AA199', 'B002BB199', 'C003CC199', 'D004DD199', 'E005EE199'],
    'Refund': [np.nan, 1, 0, np.nan, 1],
    'Fines': [1200.00, 2300.00, 750.00, 980.00, 1500.00],
    'Make': ['Lada', 'BMW', 'Audi', 'Toyota', 'Ford'],
    'Model': ['Vesta', 'X5', 'A4', 'Camry', 'Focus'],
    'Year': [2010, 2012, 2015, 2018, 2011]
})

new_fines

   CarNumber  Refund   Fines    Make  Model  Year
0  A001AA199     NaN 1200.00    Lada  Vesta  2010
1  B002BB199    1.00 2300.00     BMW     X5  2012
2  C003CC199    0.00  750.00    Audi     A4  2015
3  D004DD199     NaN  980.00  Toyota  Camry  2018
4  E005EE199    1.00 1500.00    Ford  Focus  2011

In [40]:
fines = pd.concat([fines, new_fines], ignore_index=True)
fines.tail()

     CarNumber  Refund   Fines    Make  Model  Year
925  A001AA199     NaN 1200.00    Lada  Vesta  2010
926  B002BB199    1.00 2300.00     BMW     X5  2012
927  C003CC199    0.00  750.00    Audi     A4  2015
928  D004DD199     NaN  980.00  Toyota  Camry  2018
929  E005EE199    1.00 1500.00    Ford  Focus  2011

In [41]:
owners = owners.iloc[:-20]
owners.tail()

        CarNumber     SURNAME
130  T016OX197RUS      CARTER
131  Y7649C197RUS  RICHARDSON
132  97987H178RUS       PRICE
133  Y964O8197RUS        GRAY
134  934497178RUS      COOPER

Add three new observations to owners

In [42]:
new_owners = pd.DataFrame({
    'CarNumber': ['X111XX199', 'Y222YY199', 'Z333ZZ199'],
    'SURNAME': ['Adams', 'Clark', 'Lewis']
})

new_owners

   CarNumber SURNAME
0  X111XX199   Adams
1  Y222YY199   Clark
2  Z333ZZ199   Lewis

In [43]:
owners = pd.concat([owners, new_owners], ignore_index=True)
owners.tail()

        CarNumber SURNAME
133  Y964O8197RUS    GRAY
134  934497178RUS  COOPER
135     X111XX199   Adams
136     Y222YY199   Clark
137     Z333ZZ199   Lewis

In [44]:
inner_join = fines.merge(owners, on='CarNumber', how='inner')
inner_join.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 389 entries, 0 to 388
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  389 non-null    object
 1   Refund     389 non-null    float64
 2   Fines      389 non-null    float64
 3   Make       389 non-null    object
 4   Model      389 non-null    object
 5   Year       389 non-null    int64
 6   SURNAME    389 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 21.4+ KB

In [45]:
outer_join = fines.merge(owners, on='CarNumber', how='outer')
outer_join.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 933 entries, 0 to 932
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  933 non-null    object
 1   Refund     928 non-null    float64
 2   Fines      930 non-null    float64
 3   Make       930 non-null    object
 4   Model      930 non-null    object
 5   Year       930 non-null    float64
 6   SURNAME    392 non-null    object
dtypes: float64(3), object(4)
memory usage: 51.1+ KB

Left join
This join keeps only the car numbers from the `fines` dataframe.

In [46]:
left_join = fines.merge(owners, on='CarNumber', how='left')
left_join.head()

      CarNumber  Refund   Fines    Make  Model  Year  SURNAME
0  Y163O8161RUS    2.00 3200.00    Ford  Focus  1989    GREEN
1   E432XX77RUS    1.00 6500.00  Toyota  Camry  1995  JIMENEZ
2   7184TT36RUS    1.00 2100.00    Ford  Focus  1984      NaN
3  X582HE161RUS    2.00 2000.00    Ford  Focus  2015      NaN
4  92918M178RUS    1.00 5700.00    Ford  Focus  2014     GRAY

Right join
This join keeps only the car numbers from the `owners` dataframe.

In [47]:
right_join = fines.merge(owners, on='CarNumber', how='right')
right_join.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  392 non-null    object
 1   Refund     389 non-null    float64
 2   Fines      389 non-null    float64
 3   Make       389 non-null    object
 4   Model      389 non-null    object
 5   Year       389 non-null    float64
 6   SURNAME    392 non-null    object
dtypes: float64(3), object(4)
memory usage: 21.6+ KB

проверка

In [51]:
owners['CarNumber'].isin(right_join['CarNumber']).all()

np.True_

In [49]:
pivot = fines.pivot_table(
    index=['Make', 'Model'],
    columns='Year',
    values='Fines',
    aggfunc='sum'
)

pivot

Year                   1980      1981      1982     1983      1984      1985  \
Make       Model
Audi                    NaN       NaN       NaN      NaN       NaN       NaN
           A4           NaN       NaN       NaN      NaN       NaN       NaN
BMW                     NaN       NaN       NaN      NaN       NaN       NaN
           X5           NaN       NaN       NaN      NaN       NaN       NaN
Ford       Focus   62394.59 395589.17 140383.76 63100.00 111294.59 189583.76
           Mondeo       NaN       NaN       NaN      NaN       NaN       NaN
Lada       Vesta        NaN       NaN       NaN      NaN       NaN       NaN
Skoda      Octavia 12494.59       NaN   6900.00 11594.59   1200.00  10294.59
Toyota     Camry   18500.00   8594.59       NaN  7200.00       NaN       NaN
           Corolla      NaN       NaN   2000.00      NaN       NaN       NaN
Volkswagen              NaN       NaN       NaN      NaN       NaN       NaN
           Golf    30900.00       NaN       NaN  8594.59    300.00  24000.00
           Jetta        NaN       NaN       NaN      NaN       NaN       NaN
           Passat       NaN   4600.00       NaN  3200.00  10000.00   5000.00
           Touareg      NaN       NaN       NaN      NaN       NaN   5800.00
Volvo                   NaN       NaN   6800.00      NaN       NaN       NaN

Year                   1986      1987     1988      1989  ...      2010  \
Make       Model                                          ...
Audi                    NaN       NaN      NaN       NaN  ...       NaN
           A4           NaN       NaN      NaN       NaN  ...       NaN
BMW                     NaN       NaN      NaN       NaN  ...       NaN
           X5           NaN       NaN      NaN       NaN  ...       NaN
Ford       Focus   88994.59 121900.00 95989.17 115500.00  ... 120183.76
           Mondeo       NaN       NaN      NaN   8600.00  ...       NaN
Lada       Vesta        NaN       NaN      NaN       NaN  ...   1200.00
Skoda      Octavia   600.00  26700.00      NaN  91400.00  ...   3100.00
Toyota     Camry        NaN       NaN      NaN  22400.00  ...       NaN
           Corolla 16000.00   8000.00      NaN   4000.00  ...  24000.00
Volkswagen          7400.00       NaN      NaN   7900.00  ...       NaN
           Golf         NaN   9300.00      NaN   8100.00  ...       NaN
           Jetta        NaN       NaN      NaN       NaN  ...       NaN
           Passat  15000.00  12300.00      NaN       NaN  ...   2800.00
           Touareg      NaN       NaN      NaN       NaN  ...   6300.00
Volvo                   NaN       NaN      NaN       NaN  ...       NaN

Year                   2011      2012      2013      2014      2015     2016  \
Make       Model
Audi                    NaN       NaN       NaN       NaN       NaN      NaN
           A4           NaN       NaN       NaN       NaN    750.00      NaN
BMW                     NaN   3000.00       NaN       NaN   8594.59      NaN
           X5           NaN   2300.00       NaN       NaN       NaN      NaN
Ford       Focus   88189.17 112700.00 145494.59 158894.59 203694.59 72594.59
           Mondeo       NaN  34400.00       NaN       NaN       NaN 46200.00
Lada       Vesta        NaN       NaN       NaN       NaN       NaN      NaN
Skoda      Octavia   500.00    500.00  13794.59   1900.00  46394.59   300.00
Toyota     Camry        NaN  16094.59       NaN       NaN       NaN 13000.00
           Corolla  8594.59       NaN       NaN       NaN       NaN      NaN
Volkswagen              NaN       NaN       NaN       NaN       NaN      NaN
           Golf      600.00       NaN   9300.00       NaN   2300.00      NaN
           Jetta        NaN       NaN       NaN       NaN       NaN      NaN
           Passat   3000.00   2000.00    300.00       NaN   9194.59  2100.00
           Touareg      NaN       NaN       NaN   1300.00    500.00      NaN
Volvo                   NaN       NaN       NaN       NaN       NaN      NaN

Year                    2017      2018      2019
Make       Model
Audi                     NaN       NaN       NaN
           A4            NaN       NaN       NaN
BMW                      NaN   6500.00       NaN
           X5            NaN       NaN       NaN
Ford       Focus   272200.00 285194.59 101100.00
           Mondeo        NaN       NaN       NaN
Lada       Vesta         NaN       NaN       NaN
Skoda      Octavia       NaN 156200.00   9500.00
Toyota     Camry     1000.00  13980.00  18100.00
           Corolla   9600.00       NaN  16000.00
Volkswagen               NaN       NaN       NaN
           Golf          NaN       NaN       NaN
           Jetta         NaN       NaN       NaN
           Passat        NaN       NaN       NaN
           Touareg       NaN       NaN       NaN
Volvo                    NaN       NaN  10200.00

[16 rows x 40 columns]

In [50]:
fines.to_csv('fines.csv', index=False)
owners.to_csv('owners.csv', index=False)